[package]
name = "telegram"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../../crates/base" }
common = { path = "../../crates/common" }
render = { path = "../../crates/render" }
solana = { path = "../../crates/solana" }
testing = { path = "../../crates/testing" }

dotenv = { workspace = true }
log = { workspace = true }
regex = { workspace = true}
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
teloxide = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
teloxide_tests = { workspace = true }
test-log = { workspace = true }