[package]
name = "indexer"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../../crates/base" }
common = { path = "../../crates/common" }
solana = { path = "../../crates/solana" }

serde = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
dotenv = { workspace = true }
serde_json = { workspace = true }
testing = { path = "../../crates/testing" }
test-log = { workspace = true }
tokio = { workspace = true }