services:
  postgres:
    image: postgres:17-alpine
    restart: no
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tor
    ports:
      - "127.0.0.1:5432:5432"
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-c", "max_locks_per_transaction=1024" ]
    volumes:
      - /opt/nyanbot/postgres:/var/lib/postgresql/data