[package]
name = "aggregator"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../../crates/base" }
common = { path = "../../crates/common" }
solana = { path = "../../crates/solana" }

futures = {workspace = true}
log = { workspace = true }

rand = { workspace = true, features = [] }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }

tokio = { workspace = true }
toml = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }


[dev-dependencies]
