[package]
name = "api"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
base = { path = "../../crates/base" }
common = { path = "../../crates/common" }
testing = { path = "../../crates/testing" }
solana = { path = "../../crates/solana" }
integration = { path = "../../crates/integration" }

axum = { workspace = true, features = ["ws"] }
axum-extra = { workspace = true, features = ["typed-header"] }
axum-macros = { workspace = true }
futures = { workspace = true }
log = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }

tokio = { workspace = true }
tokio-tungstenite = { workspace = true }
toml = { workspace = true }
tower-http = { workspace = true }

tracing = { workspace = true }
tracing-subscriber = { workspace = true }

url = { workspace = true }

[dev-dependencies]
test-log = { workspace = true }
tower = { workspace = true }
hyper = { workspace = true }