services:
  postgres:
    image: postgres:17-alpine
    restart: no
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=tor
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - /opt/nyanbot/postgres:/var/lib/postgresql/data

  engine:
    image: nyanbot/nyanbot
    restart: no
    environment:
      - "POSTGRES_CONNECTION_STRING=postgres://root:tor@localhost:5432/dev"
    command: /app/engine/engine /app/engine/config.toml